/**
 * 素材库的对外接口（网关 MCP 与 REST 共用）。
 *
 * 让 OmniStudio 之外的程序也能"看见"用户积累的素材：Claude Code / Codex / Cursor 之类的
 * 外部智能体经网关就能查到本机生成过的图片 / 语音 / 视频，拿到绝对路径后自行复用。
 *
 * 与内置 Pi Agent 的 `media_search` 共用 `searchMediaLibrary()`，过滤与排版口径一致；
 * 对外只读 —— 生成与导出（写文件）仍然只由用户在界面或内置 Agent 触发。
 */
import { chatImageUrl } from "../shared/server-info";
import { libraryAbsPath, searchMediaLibrary, type MediaItem, type MediaSearchParams } from "./media-tools";

export const MEDIA_SEARCH_TOOL = {
  name: "media_search",
  description:
    "Search the user's local media library in OmniStudio: images, speech (TTS) and videos — both the ones the user " +
    "generated by hand in the app and the ones generated by agents. Results are newest-first with dates, prompts, " +
    "refs and absolute file paths. Use it before asking the user to generate something again, and when the user " +
    "refers to an asset they made earlier.",
  inputSchema: {
    type: "object" as const,
    properties: {
      query: {
        type: "string",
        description:
          "Keywords matched against prompts / spoken text / model names. Omit to list what was made recently.",
      },
      kind: { type: "string", description: 'Restrict to one kind: "image" | "video" | "audio".' },
      source: {
        type: "string",
        description: '"manual" (the user made it in the UI) | "agent". Omit for both.',
      },
      days: { type: "number", description: "Only assets created within the last N days." },
      limit: { type: "number", description: "Max items (default 12, max 50)." },
    },
    required: [] as string[],
  },
};

export const MEDIA_MCP_TOOLS = [MEDIA_SEARCH_TOOL];

export function isMediaMcpTool(name: string): boolean {
  return MEDIA_MCP_TOOLS.some((tool) => tool.name === name);
}

/** 处理一次 MCP media_* 调用。 */
export async function handleMediaMcpCall(
  name: string,
  args: Record<string, unknown>,
): Promise<{ text: string; isError?: boolean }> {
  if (!isMediaMcpTool(name)) return { text: `未知的素材工具：${name}`, isError: true };
  try {
    return { text: searchMediaLibrary(readParams(args)).text };
  } catch (e) {
    return { text: `media_search 失败：${e instanceof Error ? e.message : String(e)}`, isError: true };
  }
}

/** REST 用的结构化结果：比文本多给绝对路径、可播放 URL 与毫秒时间戳，便于程序消费。 */
export type MediaAssetJson = {
  kind: MediaItem["kind"];
  id: number;
  ref: string;
  /** images 根目录下的绝对路径（文件已被删除时为 null）。 */
  path: string | null;
  /** 本地媒体服务地址（可直接播放 / 下载）。 */
  url: string;
  source: MediaItem["source"];
  createdAt: number | null;
  meta: string;
  caption: string | null;
  status: string | null;
};

function readParams(args: Record<string, unknown>): MediaSearchParams {
  return {
    query: typeof args.query === "string" ? args.query : undefined,
    kind: typeof args.kind === "string" ? args.kind : undefined,
    source: typeof args.source === "string" ? args.source : undefined,
    days: typeof args.days === "number" || typeof args.days === "string" ? Number(args.days) : undefined,
    limit: typeof args.limit === "number" || typeof args.limit === "string" ? Number(args.limit) : undefined,
  };
}

export function searchMediaAssets(params: MediaSearchParams): {
  count: number;
  assets: MediaAssetJson[];
  text: string;
} {
  const { items, text } = searchMediaLibrary(params);
  return {
    count: items.length,
    assets: items.map((item) => ({
      kind: item.kind,
      id: item.id,
      ref: item.ref,
      path: libraryAbsPath(item.ref),
      url: chatImageUrl(item.ref),
      source: item.source,
      createdAt: item.createdAt,
      meta: item.meta,
      caption: item.caption,
      status: item.statusNote ?? "done",
    })),
    text,
  };
}

/** REST 入参（查询串）→ 检索参数。 */
export function searchMediaAssetsFromQuery(url: URL): {
  count: number;
  assets: MediaAssetJson[];
  text: string;
} {
  const q = url.searchParams;
  return searchMediaAssets(
    readParams({
      query: q.get("q") ?? q.get("query") ?? undefined,
      kind: q.get("kind") ?? undefined,
      source: q.get("source") ?? undefined,
      days: q.get("days") ?? undefined,
      limit: q.get("limit") ?? undefined,
    }),
  );
}
